// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Rye4_-ioxW3nsUDrsCC0IRpUtYjqmwo',
    appId: '1:930007302731:web:832c9790e17962dab843ce',
    messagingSenderId: '930007302731',
    projectId: 'high-fashion-6d56b',
    authDomain: 'high-fashion-6d56b.firebaseapp.com',
    storageBucket: 'high-fashion-6d56b.appspot.com',
    measurementId: 'G-QHM1K79C2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cQaW18FK5x7E4M7lFnqvdO4X_N_JuS4',
    appId: '1:930007302731:android:73d3857b5a58d448b843ce',
    messagingSenderId: '930007302731',
    projectId: 'high-fashion-6d56b',
    storageBucket: 'high-fashion-6d56b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7BYczAfhp-8RHzD9quePGdk45eB9vxIw',
    appId: '1:930007302731:ios:4d941dce5a055a0bb843ce',
    messagingSenderId: '930007302731',
    projectId: 'high-fashion-6d56b',
    storageBucket: 'high-fashion-6d56b.appspot.com',
    iosBundleId: 'com.example.highFashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Rye4_-ioxW3nsUDrsCC0IRpUtYjqmwo',
    appId: '1:930007302731:web:6a8038c37b6fdca0b843ce',
    messagingSenderId: '930007302731',
    projectId: 'high-fashion-6d56b',
    authDomain: 'high-fashion-6d56b.firebaseapp.com',
    storageBucket: 'high-fashion-6d56b.appspot.com',
    measurementId: 'G-R30M1P7M9P',
  );
}
